### ISSUE TITLE
Latent list is empty

### ISSUE THREAD

**Issue by mratashi** [MushroomFleet/DJZ-Workflows#1]
Why my latent list in DJZ Load Latent is empty?
I installed with "Install via Git URL"
![image](https://github.com/user-attachments/assets/b491d994-9a24-4a0a-8092-397d387e0396)

**Comment by MushroomFleet** [comment]
you need to save them using the default ComfyCore "Save Latent" node.
You should press "R" or click refresh in comfyUI - This node will look in \output\ for any .latent files;

![image](https://github.com/user-attachments/assets/c35f2ecb-ad07-4a51-afe2-8d20046c6de4)

This node was written to eliminate the need for manual copying from \output\ to \input\.
